
name: deploy cloud functions

on:
  push:
    branches:
      - master

jobs:
  main:
    name: Build functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jsryudev/deploy-firebase-functions@v0.0.2
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT_NAME }}
      - name: Bump version
        uses: qzb/standard-version-action@v1.0.5